[project]
name = "mimicking-mindsets-v2"
version = "0.1.0"
description = "AI-Generated Insights from Influential Minds"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.109.2",
    "google-genai>=1.18.0",
    "google-generativeai>=0.8.5",
    "langchain>=0.3.25",
    "pydantic>=2.11.5",
    "pypdf>=5.5.0",
    "python-dotenv>=1.1.0",
    "qdrant-client>=1.14.2",
    "requests>=2.31.0",
    "sentence-transformers>=4.1.0",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "uvicorn>=0.34.3",
]
